server:
  port: 1424
  servlet:
    context-path: /accounts-service
spring:
  datasource:
    url: jdbc:h2:mem:learnmsdb
    driverClassName: org.h2.Driver
    username: 'learnms'
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true